spring.application.name=DatabaseConnectionUsingDataSourceObjectInSpringBoot

spring.datasource.url=jdbc:mysql://localhost:3306/sql_Practice
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#spring.datasource.url=jdbc:mysql://localhost:3306/sql_Practice
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#In properties folder
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
